url: https://www.101.camp/
baseurl: /
#baseurl: /agency-jekyll-theme/

# Site settings
title: 蟒营®101.camp
email: we@101.so
description: "蟒营®101.camp 作为永久性学习型社区运营, 通过开源网络课程框架, 持续孵化各种实用技能网络课程, 通过课程吸引学习者, 聚集学习者相互影响, 持续产生新课程/作品/社区; Operate as a permanent learning community, continue to incubate various online courses practical skill, publish open source network course framework, attract learners through courses, gather learners to influence each other, and continue to produce new courses/works/communities..."


# Team names, titles and social links
people:
- name: Zoom.Quiet
  pic: 1
  position: Lead Evangelist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: YiXuan.li
  pic: 2
  position: Lead Artist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Azeril
  pic: 3
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/zoomq
  - title: facebook
    url: https://www.facebook.com/zoom.quiet/
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: gitlab
    url: http://gitlab.com/101camp
  - title: github
    url: http://github.com/101camp

# Postal address (add as many lines as necessary)
address:
  - line: 广东省,珠海市, 香洲区
  - line: 前岛环路323号, 四号楼

# Build settings
markdown: kramdown
permalink: pretty