url: https://www.101.camp/
baseurl: /
#baseurl: /agency-jekyll-theme/

# Site settings
title: 蟒营®101.camp
email: we@101.so
description: "蟒营®101.camp 作为永久性学习型社区运营, 通过开源网络课程框架, 持续孵化各种实用技能网络课程, 通过课程吸引学习者, 聚集学习者相互影响, 持续产生新课程/作品/社区; Operate as a permanent learning community, continue to incubate various online courses practical skill, publish open source network course framework, attract learners through courses, gather learners to influence each other, and continue to produce new courses/works/communities..."

# info. in heaser
header_services: 服务
header_portfolio: 作品
header_about: 有关
header_team: 团队
header_contact: 联系
header_intro: 蟒营® Yaz工作室
header_hero: 坚持为人民服务 
header_tellmore: TELL ME MORE

#
# base:
#   Font Awesome Icons
#   https://fontawesome.com/v3.2.1/icons/
# info. in services
srv_heading: 服务
srv_subheading: Lorem ipsum dolor sit amet consectetur.
services:
  - title: 在线教育
    txt: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
    icon: fa-book
  - title: 媒体制作
    txt: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
    icon: fa-film
  - title: 社区构建
    txt: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
    icon: fa-group

# info. in services
post_heading: Portfolio
post_subheading: Portfolio

# info. in about
abt_heading: About
abt_subheading: Lorem ipsum dolor sit amet consectetur.
abouts:
  - title: 2009-2011
    subheading: Our Humble Beginnings
    txt: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
    icon: img/about/1.jpg
    layout: right
  - title: March 2011
    subheading: An Agency is Born
    txt: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
    icon: img/about/2.jpg
    layout: left
  - title: December 2012
    subheading: Transition to Full Service
    txt: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
    icon: img/about/3.jpg
    layout: right
  - title: July 2014
    subheading: Phase Two Expansion
    txt: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
    icon: img/about/4.jpg
    layout: left

# info. in about
team_heading: Our Amazing Team
team_subheading: Lorem ipsum dolor sit amet consectetur.
team_explain:  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.

# info. in clients
clients:
  - url: "#"
    icon: img/logos/envato.jpg
  - url: "#"
    icon: img/logos/designmodo.jpg
  - url: "#"
    icon: img/logos/themeforest.jpg
  - url: "#"
    icon: img/logos/creative-market.jpg

# Team names, titles and social links
people:
- name: YiXuan.li
  pic: 1
  position: 艺术总监
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Azeril
  pic: 2
  position: 媒体总监
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Zoom.Quiet
  pic: 3
  position: 首席布首官
  social:
    - title: twitter
      url: https://twitter.com/zoomq
    - title: linkedin
      url: https://www.linkedin.com/in/zoomquiet
    - title: weibo
      url: https://weibo.com/zoomquiet

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/zoomq
  - title: facebook
    url: https://www.facebook.com/zoom.quiet/
  - title: linkedin
    url: https://www.linkedin.com/in/zoomquiet/
  - title: github-alt
    url: http://gitlab.com/101camp
  - title: github
    url: http://github.com/101camp
  - title: youtube
    url: https://www.youtube.com/channel/UCuM48gcYiXK0mVpFkKSSLcg

# Postal address (add as many lines as necessary)
address:
  - line: 广东省,珠海市, 香洲区
  - line: 前岛环路323号, 四号楼

# Build settings
markdown: kramdown
permalink: pretty