url: https://www.101.camp/
baseurl: /
#baseurl: /agency-jekyll-theme/

# Site settings
title: 蟒营®101.camp
email: we@101.so
description: "蟒营®101.camp 作为永久性学习型社区运营, 通过开源网络课程框架, 持续孵化各种实用技能网络课程, 通过课程吸引学习者, 聚集学习者相互影响, 持续产生新课程/作品/社区; Operate as a permanent learning community, continue to incubate various online courses practical skill, publish open source network course framework, attract learners through courses, gather learners to influence each other, and continue to produce new courses/works/communities..."

# info. in heaser
header_services: 服务
header_portfolio: 作品
header_about: 有关
header_team: 团队
header_contact: 联系
header_intro: 蟒营® Yaz工作室
header_hero: 坚持为人民服务 
header_tellmore: TELL ME MORE

#
# base:
#   Font Awesome Icons
#   https://fontawesome.com/v3.2.1/icons/
# info. in services
srv_heading: 服务
srv_subheading: Lorem ipsum dolor sit amet consectetur.
services:
  - title: 在线教育
    txt: 蟒营®开源网络课程框架, 经12年迭代, 能帮助学员重建自学节奏, 对任何实用技能都可以基于网络资源自学获得, 再也不用上任何网课;
    icon: fa-book
  - title: 媒体制作
    txt: 从播客到短视频, 或是课程演示视频, 都有专门小组以及专业软件配合专用硬件快速交付; 当然一个完备的剧本/脚本是前提;
    icon: fa-film
  - title: 社区构建
    txt: 无论企业内外, 规模大小, 凡是以具体学习/技能目标为核心的在线/线下社区, 都有丰富经验可以具体分享.
    icon: fa-group

# info. in services
post_heading: 具体作品
post_subheading: 索引主要作品类别, 更多具体服务项目, 欢迎留言或是邮件 we@101.so 详细沟通.

# info. in about
abt_heading: 有关故事
abt_subheading: 其实自称/Yaz曲艺团, 真正云团队, 以一个核心愿景粘合起来...
abouts:
  - title: 2018.12.25 ~
    subheading: 蟒营®101.camp 再次出发
    txt: 还是在老学员提议下, 大妈 发布蟒营®开源网络课程框架, 并重构原／Python入门班 变成 “蟒营®编程思维提高班 Python版” 开始独立发布/运营; 围绕这一网络课程, Yaz 衍生出一系列服务, 未来还将继续和学员们一起探索.
    icon: img/about/1.jpg
    layout: right
  - title: 2017.4.1
    subheading: 自怼圈发布
    txt: 再次设计了不完全体“Python入门班”主持/顾问了4期后被关闭, 大妈和班长/YiXuan.li 营造的氛围却也吸引不少老学员, 大家倡议下, 利用“小密圈”这一收费社群平台, 创建了 DebugUself ~ 自怼圈/长期自学社区; Yaz曲艺团初见风格, 在各种渠道中引发了无数梗.
    icon: img/about/2.jpg
    layout: left
  - title: 2014.10.1
    subheading: 在书友群遇见...
    txt: 那时 YiXuan.li 刚刚回国, 还没有成为班长; Az 也刚刚入职, 还没能成为颜值担当; 大妈因为 PyCon中国 大会的筹备意外进入一个号称必须有博士或是硕士双学位才能进入的微信群;开始长达两年多的群口相声实践;
    icon: img/about/3.jpg
    layout: right
  - title: 2006.4.20
    subheading: “大妈”诞生
    txt: 在 CPyUG 社区邮件列表中, 有关 woodpacker,.org.cn 使用吐糟中, ZoomQuiet 随口回复:“...有一群极认真的大妈在维护...”;结果其它社区积极分子无人承认,只有大妈认领了这一称号...
    icon: img/about/4.jpg
    layout: left

# info. in about
team_heading: Our Amazing Team
team_subheading: Lorem ipsum dolor sit amet consectetur.
team_explain:  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.

# info. in clients
clients:
  - url: "#"
    icon: img/logos/envato.jpg
  - url: "#"
    icon: img/logos/designmodo.jpg
  - url: "#"
    icon: img/logos/themeforest.jpg
  - url: "#"
    icon: img/logos/creative-market.jpg

# Team names, titles and social links
people:
- name: YiXuan.li
  pic: 1
  position: 艺术总监
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Azeril
  pic: 2
  position: 媒体总监
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Zoom.Quiet
  pic: 3
  position: 首席布首官
  social:
    - title: twitter
      url: https://twitter.com/zoomq
    - title: linkedin
      url: https://www.linkedin.com/in/zoomquiet
    - title: weibo
      url: https://weibo.com/zoomquiet

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/zoomq
  - title: facebook
    url: https://www.facebook.com/zoom.quiet/
  - title: linkedin
    url: https://www.linkedin.com/in/zoomquiet/
  - title: github-alt
    url: http://gitlab.com/101camp
  - title: github
    url: http://github.com/101camp
  - title: youtube
    url: https://www.youtube.com/channel/UCuM48gcYiXK0mVpFkKSSLcg

# Postal address (add as many lines as necessary)
address:
  - line: 广东省,珠海市, 香洲区
  - line: 前岛环路323号, 四号楼

# Build settings
markdown: kramdown
permalink: pretty